2024-12-02T18:35:10.496973+0000 INFO 9424 Created database engine for db quotesdbtest_whistleask, user quotesdbtest_whistleask, address pcyp4.h.filess.io:3307
2024-12-02T18:35:11.188253+0000 INFO 9424 Database schema initialized successfully.
2024-12-02T18:35:11.267420+0000 INFO 9424 Tables in the database: ['TestTable', 'apilogs', 'authors', 'confirm_codes', 'quotes', 'quotes_tags_link', 'tags', 'users']
2024-12-02T18:35:11.267420+0000 INFO 9424 All required tables have been created successfully.
2024-12-02T18:35:32.360275+0000 ERROR 9424 Code for fastuperza@gufum.com does not exist.
2024-12-02T18:35:32.767746+0000 ERROR 9424 Error inspecting database engine: (pymysql.err.OperationalError) (1226, "User 'quotesdbtest_whistleask' has exceeded the 'max_user_connections' resource (current value: 5)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-12-02T18:35:38.431500+0000 ERROR 9424 Code for fastuperza@gufum.com does not exist.
2024-12-02T18:35:38.709601+0000 ERROR 9424 Error inspecting database engine: (pymysql.err.OperationalError) (1226, "User 'quotesdbtest_whistleask' has exceeded the 'max_user_connections' resource (current value: 5)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
