2024-11-22T06:54:28.543905+0000 INFO 130000316977280 Created database engine for db quotesdbtest_whistleask, user quotesdbtest_whistleask, address pcyp4.h.filess.io:3307
2024-11-22T06:54:29.280419+0000 INFO 130000316977280 Database schema initialized successfully.
2024-11-22T06:54:29.373766+0000 INFO 130000316977280 Tables in the database: ['TestTable', 'authors', 'quotes', 'quotes_tags_link', 'tags', 'users']
2024-11-22T06:54:29.374223+0000 INFO 130000316977280 All required tables have been created successfully.
2024-11-22T06:55:20.470827+0000 ERROR 130000316977280 Error executing statement 'SELECT users.id, users.username, users.password, users.access, users.time_created, users.time_updated 
FROM users 
WHERE users.username = :username_1': (pymysql.err.OperationalError) (1054, "Unknown column 'users.access' in 'field list'")
[SQL: SELECT users.id, users.username, users.password, users.access, users.time_created, users.time_updated 
FROM users 
WHERE users.username = %(username_1)s]
[parameters: {'username_1': 'user1'}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
